---
- name: Example with discouraged free-form syntax
  hosts: localhost
  tasks:
    - name: Create a placefolder file
      ansible.builtin.command: # <-- don't use free-form
        chdir: /tmp
        cmd: touch foo
    - name: Use raw to echo
      ansible.builtin.raw: echo foo # <-- don't use executable=
      args:
        executable: /bin/bash
      changed_when: false
