---
- name: Problematic example
  hosts: localhost
  vars:
    foo: "{{some|dict2items}}" # <-- jinja[spacing]
    bar: "{{ & }}" # <-- jinja[invalid]
    blub: "{{ foo | bool }}" # <-- jinja[spacing] - 'when' has implicit templating
  tasks:
    - name: Echo a message
      ansible.builtin.command: echo hello
      changed_when: false
