---
- name: This is a playbook # <-- name key should be the first one
  hosts: localhost
  tasks:
    - name: A block
      when: true # <-- when key should be before block
      block:
        - name: Display a message
          ansible.builtin.debug:
            msg: Hello world!
